### ISSUE TITLE
Prison Labor compatibility: working prisoner does job he doesn't know how to do

### ISSUE THREAD

**Issue by dazian** [jptrrs/HumanResources#105]
![20201203184246_1](https://user-images.githubusercontent.com/75456657/101104485-3d523c00-3599-11eb-9372-eff83016cf25.jpg)

This prisoner is making pemmican without knowing the pemmican technology.

I was able to reproduce this with the following mods and steps:

Modlist in order: Harmony, Core, Royalty, HugsLib, Prison Labor, ResearchPal, [JPT] Human Resources

- Started a new Lost Tribe game
- Disallowed cooking for all pawns
- Built a prison cell attached to a room with a campfire, with the door to the prison cell held open
- Set a bill to make pemmican on the campfire
- Populated the room with ingredients for pemmican, which the prisoner can reach
- Generated raids until an enemy pawn without knowledge of pemmican was generated
- Downed and captured that pawn
- After the enemy was taken prisoner, set his schedule to work and set him to cook
- Prisoner began making pemmican as shown in the screenshot

No errors were generated related to this.

Save: [prisonlabor hr test.rws.txt](https://github.com/jptrrs/HumanResources/files/5639788/prisonlabor.hr.test.rws.txt)

**Comment by jptrrs** [comment]
Thanks for reporting this, dazian. That savefile was very handy! 
We had every npc exempted from the knowledge restrictions in order not to mess with the normal game mechanics. But it's true it gets weird when it comes to prisoners. So I extended the restrictions for them too. Should be online soon, on our next update.
Please, take notice of issue #96, which also affect prisoners from Prison Labor and remains unsolved (because it's out of my hands).
