### ISSUE TITLE
Inconsistency between the description and research speed multiplier calculations?

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#106]
The description of this mod states: "If the tech you're researching has any pre-requisites, your pawns will only be able to proceed if they already mastered those. On the other hand, if what they are researching is either itself a pre-requisite to something they already know, their research speed is doubled."

I modeled a situation where the [Electricity] tech is already researched and known by my researcher named Anfisa.
When I assign Anfisa to research [TubeTelevision] or lets say [AirConditioning], for which the prerequisite is [Electricity], her research speed is doubled, although she doesn't know anything for which [TubeTelevision] would be a prerequisite, which goes against the description statement.

Another, more detailed example, where Anfisa researches the prerequisite to what she already knows (and there are no research speed increase), I sent you in discord.

**Comment by Reiquard** [comment]
If you still to get to this and **_IF_** the calculations of this multiplier are still subject to change in the future, wouldn't it be better to wrap them in a method for the sake of compatibility stability?
I see it something like this:

	public static float PrerequisitesMultiplier(ResearchProjectDef tech, Pawn researcher)
	{
		Dictionary<ResearchProjectDef, float> expertise = researcher.TryGetComp<CompKnowledge>().expertise;
		foreach (ResearchProjectDef ancestor in expertise.Keys)
		{
			if (!ancestor.prerequisites.NullOrEmpty() && ancestor.prerequisites.Contains(tech)) //I think this is correct
			{
				return 2f;
			}
		}
		return 1f;
	}

**Comment by jptrrs** [comment]
I see what you mean. I don't expect changes nor variations to this multiplier in the future, but if it ever comes to that this might be a good solution. 
I corrected the issue, and since the fix will effectively make most research tasks twice as long, I decided to implement something I've been thinking about forever, on this same method: to get the TechLevel multiplier from the pawn itself, instead of his faction's. This will make a researcher faster as he reaches more advanced technologies. Hope this balances the research speed a little.
