### ISSUE TITLE
Harvesting plants without appropriate knowledge

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#114]
I have already drawn your attention to the fact that pawns can **sow** plants without appropriate knowledge, and you have fixed this.
But (_I'm not sure if this is intended_) pawns without knowledge in say devilstrand can **harvest** it.
![screenshot23](https://user-images.githubusercontent.com/62316596/101709503-a4dc2000-3aa0-11eb-91e1-ff3aac2cfebb.png)

**Comment by Reiquard** [comment]
Not quite an issue, more of a suggestion.
I liked your idea

> ..to get the TechLevel multiplier from the pawn itself, instead of his faction's. This will make a researcher faster as he reaches more advanced technologies.

In current realisation pawn can get a massive bump in techlevel understanding after studying just a single technology.
If the pawn's knowledge techlevel is neolithic, an industrial project research has a 50% speed multiplier, but after the pawn completes this research and learns it's secrets, he/she/it immediately becomes a quick thinker.
It's like.. 
"Hey, I just learned about drug production.. And I already feel the full power of industrial progress!"
//disclaimer: don't take it as a drug advertising, it's just "drug production" is on industrial techlevel.. ;]
So I would suggest making this transition smooth:
If the pawn's knowledge techlevel is neolithic and it learns higher techlevel project, research speed multiplier raises for say 5%
Or if this implementation is quite complex, then just award the pawn a new techlevel after X studied projects or Y% of that techlevel total number of techonologies

Also.. as of now the game stops complicating the research process after the industrial techlevel
```cs
	public float CostFactor(TechLevel researcherTechLevel)
	{
		// get the lowest: [project techlevel] or [4]   (Neolithic = 2; Medieval = 3; Industrial = 4)
		TechLevel techLevel = (TechLevel)Mathf.Min((int)this.techLevel, 4);
		if ((int)researcherTechLevel >= (int)techLevel)
		{
			return 1f;
		}
		int num = techLevel - researcherTechLevel;
		return 1f + (float)num * 0.5f;
	}
```
I see it logical and interesting to also raise this threshold to 6 or at least 5 if it's possible.
Thanks for your attention.

**Comment by jptrrs** [comment]
Hi There!
About the first issue, harvesting is not supposed to be locked behind technologies. We decided that early on, since harvesting is such an important game mechanic and messing with it could have disastrous consequences. Even the vanilla skill limit doesn't apply to harvesting plants, just sowing. We didn't want to mess with that.
About the Tech Level, I had the exact same thoughts. A smoother transistion would be cool, but I decided not to overthink the solution and just implement the basic idea and see how it goes. 
Observe that, for a tribal trying to learn an industrial tech, the difference between the vanilla scheme and ours, with the pawn that learned just one industrial tech, is the research speed doubles on ours. That's exactly the same effect you identified on issue #106, and that speed buff didn't seem to cause that much imbalance. Before you checking the code, no one even noticed. It looks like one of those "realisms" that don't necessarily translates to the game becoming more interesting.
But we might revisit that in the future.
