### ISSUE TITLE
Error when used with the unspeakable mod

### ISSUE THREAD

**Issue by Afterthought-btw** [jptrrs/HumanResources#115]
I don't know what your position is on the unspeakable mod (RJW), so if you have some of the qualms a few other people have with it then just ignore this bug report, I guess. Even then there may be other mods that do something similar, so it might be useful to be aware of this. I'm getting this error relatively repeatably. Seems to be caused when a pawn from another faction comes on to the map as I've got it both from raids and trade caravans.

https://gist.github.com/HugsLibRecordKeeper/af5bdff0fbe0f0e3ed4ef30975d2d326

The way I repeat it is to load all the bare bones mods for Human Resources, and then add RJW as well. Start a new map, and then I send in 10 trade caravans via dev mode > incident . Usually a number of the caravans have this error and don't spawn.

**Comment by jptrrs** [comment]
Yeah, I'd rather wait the error pop up in a mod I can download and test without having to deal with rape, misogyny and a complete disregard for civil standards.

**Comment by Afterthought-btw** [comment]
That's fine. Honestly, had I heard what is said about RJW before I tried it I probably never would have. As it was, I was naïve, knew nothing about it, and used it because the children and pregnancy mod I used stopped implementing its own pregnancy mechanic and suggested using this for that functionality. To be fair, most of what is said of it misses the mark though. I only use it for pregnancy and disable the rest of the stuff, but the other stuff looks to me like sex positive fetish/kink stuff rather than anything else. That's really easy to turn people off (for want of a better phrase), though obviously. I'm just more permissive than most people when it comes to stuff that doesn't harm people in the real world I guess.

It certainly does a better job at disincentivising the morally abhorrent stuff in it than base Rimworld does, however. There's nothing as abhorrent as organ farms, for example, nor are any of the nasty traits remotely useful (unlike, say, cannibalism); quite the opposite.

**Comment by jptrrs** [comment]
Interesting.

**Comment by markusnotaking** [comment]
lol... "unspeakable mod" 
I wanted to report the problem, but I see that the question has already been submitted.

An error occurs when spawning pawns. I got an error caused by the spawn of allies from the tribe. 
Near the spawn place ( that caused the error ) the user interface and the pawns disappear. Some pawns can disappear in some places and appear in others as they move... under something invisible. 
I began to check and spawn the tribes warriors and about every fifth (or less) pawn causes an error.

RJB, No water no Life and Dubs Bad Hygiene are must have mods (for me), because all of them adds realistic needs. Each need adds more and more problems and difficulties, which means the game is more and more interesting. 
The need added by RJB is no exception and gives a lot of troubles especially at the start, and especially without cheating mods that change vanilla settings.

Due to the lack of updating No water no Life mod, as well as very strong FPS drawdowns during rain (with this mod), I had to remove it from my list (I recently returned to the game.) ... It was a difficult decision and the rimworld became noticeably worse! The thirst added by Dubs Bad Hygiene cannot replace the thirst from No water no Life even close ...  I'm very upset. 
I like Human Resources too much but I really do not want to lose one more need.

**Comment by jptrrs** [comment]
markusnotaking: 
Well, you did not provide your game log, so I can't be sure if the error you encoutered was the same as Afterthought-btw did. On the other hand, your description of its consequences reminded me of another past issue. This led me to revisit this issue and think of a possible cause. I ended up making a small change to the knowledge generation algoritm to protect it from the possibility of having pawns generated with non-standard childhood stories. IF that was the case, you might find the latest version, 0.31, corrected it. I won't test myself, I still don't want to mess with that mod. But if you could, please let me know the results. Thanks.

**Comment by markusnotaking** [comment]
I checked the game after new update. No more errors occur. 
I want to say that you made an amazing mod, I really liked it.

**Comment by jptrrs** [comment]
Good, then that was it!
I'm glad you like it :-)

**Comment by Afterthought-btw** [comment]
Latest update looks to have fixed it. I'm guessing said unspeakable mod must generate less than 2 childhood skills relatively often.
