### ISSUE TITLE
Custom categories break training mechanic for melee weapons

### ISSUE THREAD

**Issue by LaZeR4312** [jptrrs/HumanResources#119]
Almost all of the melee weapons in my modlist are not available in the menu for the training dummy, and I get errors on startup regarding how no-one will know a significant quantity of the research projects added. There is a partial workaround through the "learn in groups" setting allowing knowlege of dozens of weapons because somebody swung an axe for a couple of hours, but this more-or less defeats the purpose of training proficiencies in the first place. This is only a partial fix because it does not work for everything.

I moved the mod to the bottom of my modlist, realizing that may be the root cause since only vanilla weapons populated the list, but while about 5 or 6 new weapons popped up in the list it is nowhere near the totality. The training dummy and the storage menus work the same way, and most of the excluded weapons are in different, custom categories for some reason. Since these are excluded from the available categories I'm pretty sure that's the root of the issue. I do not have this problem for ranged weapons,

**Comment by jptrrs** [comment]
Hi. Please, follow these instructions so I have enough information on the issue: https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/

**Comment by LaZeR4312** [comment]
I knew to do those things, reading that is how I came to the real report page. If I wanted to waste our time, I would have commented on the steam page. 
Aside from the knowledge problem, which is not the focus of my issue, there isn't anything happening in the logs that could explain this issue. Admech Armoury divides weapons into subcategories depending on which alien faction it is meant to belong to. Since these are not initialized in the whitelist (which is necessary or else you might have pawns trying to train to use components as a weapon) they simply aren't available to be trained in the list. Since the game isn't recognizing an issue, there wouldn't be anything in the logs that could be of help. (and I checked, there aren't any references to this mod except for this error
      "[HumanResources] No relevant skills could be calculated for BrainWiring. It won't be known by anyone.
       (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)"
and the others like it, which I'm certain are not directly related.

If anything in particular is still unclear, or if this is an issue you can't help me with, then I apologize.

**Comment by jptrrs** [comment]
Dude, just follow what I already layed out there. Until then, you WILL be wasting our time. Don't forget to link the conflicting mod. Thx.

**Comment by LaZeR4312** [comment]
Log:
[Player.log](https://github.com/jptrrs/HumanResources/files/5782346/Player.log)
Conflicting Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1541438614&searchtext=admech+armoury

Everything is up to date and the list is pared down to bare essentials. The error is readily reproducible simply by loading these mods and trying to equip or train an unsupported melee weapon, obviously after researching the tech, where the prompt says they cannot comprehend it and M2 on a training dummy (after placing bills of all kinds and ensuring all enumerated items are permitted, of course) claims no weapons can be trained despite the item in question being present, accessible and unforbidden.
Test pawns are capable of violence and research and are selected for the study worktype.

**Comment by jptrrs** [comment]
Alright, thanks for the info. See, it wasn't so hard ;-) 
From your log, it seems you had more than the "bare essentials" running, I was able to load just HR and its dependencies along Adeptus Mechanicus: Armoury. But it doesn't matter, I figured out what was going on. This was the line I needed from you:
``"[HumanResources] This is what we know: 173 technologies processed, 14 basic crops, 64 basic weapons + 36 that require training."``
You can get more details if you turn on the verbose logging, but essentially the weapons were correctly processed, they just didn't show up on the bill filter. This is because the mod author decided to ignore the existing rimworld weapon categories and made up a completely paralel system. I wrote a patch to circumvent this and it will be up with the next mod update. 
The patch will also prevent wepons tagged with "Power Weapon" from being considered commom knowledge, so they'll require training even if they're not locked behind research. If you believe there are other commom weapons that should get the same treatment, please turn on development mode, open the tech tab on any pawn and roll the mouse over the weapons in question. This will show you their tags. If you find a tag that identifies reliably the ones that should require proficiency, it pretty easy to add them to the patch.
