### ISSUE TITLE
All online knowledges disappear upon reinstalling the network server to another spot

### ISSUE THREAD

**Issue by panyutsriwirote** [jptrrs/HumanResources#146]
Reinstalling the network server causes all online knowledges to disappear, forcing the player to re-document every knowledge previously kept on it

Confirmed to be reproducible on my computer with only Human Resources and its dependencies loaded (I use ResearchPal - Forked)

Start a game, use dev mode to give myself a terminal and a server, document whatever knowledge my characters start with, the server becomes non-empty, relocate it and BOOM, the server is empty

Not sure if this is a bug or an intended feature, but I don’t think data should just disappear whenever I unplug and relocate the server somewhere else

**Comment by tophd7** [comment]
From reading the code it seems as this is the expected thing, as when the server is moved it checks for a backup (idk how to backup, will read more into the code)

Edit: It appears that when you move it the game no longer considers it as an item on the map causing it to instantly purge all the techs

**Comment by jptrrs** [comment]
Thanks for reporting this, PanyutSriwirote. Tophd7 is right, that was expected, because the game deals with the server de-spawning the same way if it is destroyed or just uninstalled. Buuuut... that doesn't mean we can't work our way around it! ;-)
So I made the server retain its memory when uninstalled. The techs will still be removed when it is offline, but they will be restored when it is re-installed. New update is online now.
