### ISSUE TITLE
Rimworld Of magic weapons not included in training bill

### ISSUE THREAD

**Issue by JDRafferty** [jptrrs/HumanResources#149]
These weapons do not appear on the training dummy recipe bills and so can never be learnt unless pawn is spawned naturally with it.
Thrum bow
elephant bow
thrumbo axe
elephant spear
blazing power staff
defender staff

Link to Rimworld of Magic
https://steamcommunity.com/sharedfiles/filedetails/?id=1201382956

Also is their a way to change the base technology in the def files for a weapon? Things like heavy clubs from the Vanilla expanded tribal weapons for some reason use electricity as its base technology when it's weapons tags are NeolithicMeleeAdvanced which doesn't makes sense for a tribal to know electricity to use a weapon like that.

thanks in advance.

**Comment by jptrrs** [comment]
Ok, thanks for the list and the link!
I looked into it and realized the _Thrum Bow_ and both staffs are actually classified as basic commom weapons, that is, they don't require training at all. Activate the hammer button to see them on the tech tab.
The others were missing because Torann decided to create his own weapon categories rather than using the vanilla ones. But no sweat, I'm including a patch to take that into account when _A RimWorld of Magic_ is loaded. It will be up soon, with v0.38
>Also is their a way to change the base technology in the def files for a weapon?

Other than actually changing the required technology for creating them, no. But the _heavy club_ base tech isn't electricity, but _Smithing_.

**Comment by JDRafferty** [comment]
Thanks for the response :) keep up the good work
