### ISSUE TITLE
Neolithic and medieval variants for books and study desks

### ISSUE THREAD

**Issue by Grondyne** [jptrrs/HumanResources#157]
Circa about a several weeks ago i seek a mod, that makes vanilla research system more immersive, but i discover this amazing mod instead. However, when i played in rimworld with this mod, my tribal pawns found that there are no Neolithic variants of study and Research desks in this mod, only electrified industrial-style desk, it is very unrealistic and destroy the game experience. It been very cool, if you can add this variants to this mod or made compatibility patch to add functionality of Human Resource to RimWriter mod. Also it be amazing if tribal pawns that has no writing skills can transfer neolithic techs to eachother by social skills, like in prehistoric times.

Sorry if my english is bad.

**Comment by jptrrs** [comment]
Thanks for your suggestions, Grondyne. This channel is for reporting errors, bugs, and other functional issues with the mod, but I'll take a minute to answer you.
I don't share your perspective on the supposed need for everything to have a different variant for each era. If the base game followed this directive it would be extremely bloated!! Also, the study desk isn't electrified, just as the vanilla research bench (which is merely re-skinned for this mod).
Moreover, let me clarify: none of my mods strive for "realism". I don't consider it to be a valid guide on how to design fun game mechanics, as it usually leads to useless, boring features. No game will ever be realistic because, well, they're games! Full realism means not playing a game, so that's not what makes one enjoyable.
That being said, I don't plan on integrating it with RimWriter or modifying the knowledge transmission mechanic. And I understand if that makes you decide Human Resources is not what you're looking for.
Thanks for reaching out, anyway!
