### ISSUE TITLE
Unable to store books in bookshelves

### ISSUE THREAD

**Issue by 2020jji** [jptrrs/HumanResources#165]
I wanted to move my bookshelf to a new location, but when I uninstalled the shelf, the books popped out, now it's impossible to move them back on the shelves.

![RimWorldWin64_0FvO1zUQUa](https://user-images.githubusercontent.com/92397869/156415193-0d63d6bd-f29d-4538-83b3-4e5d5ae996c5.gif)

Here's my log:
https://gist.github.com/HugsLibRecordKeeper/865d44cfc36a96b8c9779617d0c229f7

**Comment by 2020jji** [comment]
Figured it out! It was a conflict with "Favorites!".

**Comment by 2020jji** [comment]
Never mind, seems like the issue still persists...

**Comment by 2020jji** [comment]
Finally figured out the incompatible mod! It was "Pick Up And Haul"...

**Comment by jptrrs** [comment]
Hi. It seems that's due to some change they made on their last update. Someone made this recommendation on our steam page, maybe it helps:
"For people having issues with Pick up and haul - if you are using While you're up / PUAH+ - go to while you're up settings and deselect "Use and improve Pick up and haul". It should now allow you to put books on the bookshelf. I could even enable it back again and pawns could still put books in afterwards. "

**Comment by 2020jji** [comment]
Just tried it out and it's perfect now! Thanks, and I love this mod!

**Comment by modulozero** [comment]
Hey, FYI, this doesn't seem to work for me :( Worse, if I ever manage to put the book on the shelf (it seems to happen if the pawns don't find anything else to haul at the same time) _the entire catalog disappears_, and after save & reload, the entire bookshelf will be gone. This does _not_ count as destruction - I still have the technologies from the bookshelf, they just no longer exist as books.

See also my [gist](https://gist.github.com/3a056db5de790a32777e2009416e79c2)

**Comment by modulozero** [comment]
For what it's worth, it doesn't seem to be an issue if only [While You're Up](https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453) is present - but [PUAH](https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058) seems sufficient. Unfortunately the issue is tricky to reproduce - it seems to require the PUAH mechanics to activate (i.e. take things to different storages at once), but _sometimes_ the pawn will drop the book when just carrying the book - other times it works as it should.

I _think_ a satisfactory fix would be preventing PUAH for working on books at all - unfortunately, I have no idea how to make a PR that can do that within the amount of time I have :(

**Comment by jptrrs** [comment]
Let me know I you find a reliable way to reproduce the issue, bc I can't.

**Comment by modulozero** [comment]
I'll try to reproduce it, though probably not immediately - a bit too brain-drained to do proper triage right now :(
