### ISSUE TITLE
[Rimthreaded] "Study" related jobs cannot be automatically assigned to pawns

### ISSUE THREAD

**Issue by AichiChikuwa** [jptrrs/HumanResources#167]
I've reported this [bug](https://github.com/cseelhoff/RimThreaded/issues/759) to Rimthreaded's repo too. Guess it's more on their side?

With Rimthreaded, they'll never do study jobs unless prioritizing them manually. Priorities in the Work tab don't affect the bug. Both forked ResearchPal and forked Research Tree can occur this bug.

Start a new game with HumanResources and Rimthreaded (and dependencies of course), set up desks, bookshelves, bills, techs to documentation/study, and you'll see the bug happen.

If a job is forced, they'll do it normally, but any interception (like drafting-undrafting, need to entertain/eat/sleep) will break the job. One exception is that if a pawn has an unfinished book, he/she will work on it normally until it's done. The next documentation job won't queue up tho.

Here's the [log](https://gist.github.com/HugsLibRecordKeeper/6d64b771188e229d1ca3a297a96555c5) but I doubt if it helps as there's no error.

**Comment by jptrrs** [comment]
Thanks for the info. I'll take a look when I can.

**Comment by jptrrs** [comment]
It seems that's not exactly an issue with Human Resources, but a known general issue with Rimthreaded. It's been reported to them since September last year (https://github.com/cseelhoff/RimThreaded/issues/669), and it seems it's already on their high priority to-do list.
The only thing I can do about it is marking Rimthreaded as incompatible. Sorry.
