### ISSUE TITLE
Unknown mod incompatibility

### ISSUE THREAD

**Issue by ShauaPuta** [jptrrs/HumanResources#176]
Hello
In the recent updates, something changed on the research and tech levels correct? Something in that is breaking pawn generation for me. When a pawn tries to spawn, there's an exception generating knowledge for them, which causes the spawned pawn to break the game.
I have a huge modlist, so the cause is for sure a mod incompatibility with one of them. I am sorry, but I was unable to find which one. 
I am switching to an older local copy of human resources for the time being, but I hope the log I'm adding helps you to figure it out somehow.
I am including a log from the main menu. The last message there is related to it I suppose.
![image](https://user-images.githubusercontent.com/62623539/174849554-be85147b-57dd-4162-9e71-1f594dddf0b7.png)

https://gist.github.com/f9673db2b044edcddfe12d93fd4a86a6

I was at least two weeks away from rimworld, so I didnt notice it sooner. thanks for your time

**Comment by jptrrs** [comment]
Thx for the log. Yeah, we'd need to isolate the offending mod to make real
progress... Here's what I can tell from you log:
The failed pawn spawning is the consequence, not the cause. It's happening
because of that previous error at startup, the one on your screenshot,
which prevents the mod from initializing properly. And if it started
happening with the update, I can tell from the place where it happens that
there's something to do with the new support for Vanilla Furniture Expanded
- Art.
Then, I found this at your log:
"[ModMetaDataCleaner] Removed 534 Metadata and cleaned 288 PreviewImage."
Comes with a list which includes VFE-Art and a bunch of others.
Whatever mod is removing the metadata, I bet that's the culprit. We need
that metadata, reading it is the way we identify what other mods are
running and act accordingly. You remove the data, you'll prevent a lot of
mods from detecting and reacting to each other. It's a dumb idea.
Find what mod is doing that, disable it or turn that feature off, and try
again. I bet it will get solved.


João Pedro

**Comment by jptrrs** [comment]
Heads up: thanks to info provided on issue #175, I was able to identify and fix a bug that would lead to that same error you found. The mod was updated. It might or might not have been the same thing that was happening here, but it will probably mute that error anyway. Regardless, I still recommend disabling that [ModMetaDataCleaner] mod to avoid other issues that would have been less evident.
