### ISSUE TITLE
Weapons practise messes up weapons assignment

### ISSUE THREAD

**Issue by seona13** [jptrrs/HumanResources#2]
When a pawn goes to practise with a weapon at either the Training Dummy or Target Stand, they drop their assigned weapon to take up the weapon they want to practise with. They then keep this weapon afterwards. This causes a couple of problems that I've noticed:

- Because they don't go back to their previous weapon, I end up with pawns not wielding what I want them to. It's even worse if they get interrupted before they gain proficiency, because now they are wielding a weapon they can't use.

- Even if they have a weapon already in their inventory, if they go back to train some more they will pick up another one. I had one pawn wandering around with three longswords at one point. (Not sure if this is related to Simple Sidearms though... it might be a separate issue.)

**Comment by jptrrs** [comment]
Hi, Seona. 
I've tested the mod extensively along Simple Sidearms and I didn't observe this behaviour. Both _learn_ and _practice_ routines should end with the pawn dropping the weapon. What you're experience might be due to some other mod interfering or, maybe, some Simple Sidearms configuration. I'd ask you to try loading only Human Resources to see if it persists, then adding other mods one by one, until the issue arises again. When it does, please hit Ctrl+F12 and post the link here, so I can look for the cause. Thanks!

**Comment by jptrrs** [comment]
Since I couldn't reproduce this issue and you didn't send me the log, I presume the matter is solved. If you're still experiencing it, please try this: https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/
