### ISSUE TITLE
Resrict "Study technology" by skill level?

### ISSUE THREAD

**Issue by seona13** [jptrrs/HumanResources#3]
Is it possible to restrict the "study technology" job by skill level? It would be nice, for example, to only have my crafters learning how to make advanced items or only have my science-gurus learn how to make top-tier drugs (because they're the only ones with the necessary skills to do the job once it's learned). At the moment even my menial worker (who hauls and cleans full-time) is learning all of these techs he's never going put into practise.

I'm guessing it's probably a little trickier than with most workbench jobs, since you'd have to be able to select the skill on a per-job basis instead of the skill being inextricably linked to the job, but I figured it was worth asking.

**Comment by jptrrs** [comment]
Yeah, that would be tricky. But you can restrict the bill to a particular pawn (instead of "Any Worker"), and you can have multiple study bills on your study desk, one for each pawn you're training. I recommend that! Also, install [Better Workbench Management](https://steamcommunity.com/sharedfiles/filedetails/?id=935982361). Among other things, it allows you to rename the jobs, so you can have something like "Jane's homework" separated from others.
