### ISSUE TITLE
Unable to select anything on screen [OnGUI() exception]

### ISSUE THREAD

**Issue by ButternCream** [jptrrs/HumanResources#51]
I'll be honest this _may_ have nothing to do directly with this mod since I am using so many. i'll try and reproduce it to see what mods caused issues but that may take a while. 

Basically what happened was a horse manhunter spawned, I clicked on to jump to location, and somehow broke the GUI.I couldnt select anything on the screen. (Pawns, animals, plants, etc.) I noticed exceptions from this mod as it occurred in the log. I had manhunter events prior with no issues. 
[Here is the log](https://gist.github.com/HugsLibRecordKeeper/3a4c37f2ac2518aa41f81fb036db4fd7#file-output_log-txt-L3912)
**Line 3912** is when I started having issues (the horse spawn is right below it)

I also do notice that `[HumanResources] <pawn> tried to learn a null project.` shows up quite a bit. 

I'll attach my save incase you want to take a look.

Feel free to add this to low priority backlog. I'll try some games with minimal mods and see how it goes.

Sorry I didnt quite _exactly_ follow the discussion on the steam page. Enjoying this mod though!

[Great Lib.zip](https://github.com/jptrrs/HumanResources/files/4861265/Great.Lib.zip)

**Comment by jptrrs** [comment]
Thanks for the log and the file, ButternCream. Yeah, it would be better if you were able to test this without other mods, but I suspect this will be difficult. I say this because I've seen this error before, and it shouldn't be happening anymore. Actually there's more than one problem here, but the one that causes the screen bug is related to an Imperial pawn that has spawn at some point but the game couldn't generate an expertise list for him. Unfortunately, that causes a catstrophic UI fail when he appears on screen. I found one on your file and deleted him, please check if it's solved on this file: 
[Great Lib - DEBUGGED.zip](https://github.com/jptrrs/HumanResources/files/4861817/Great.Lib.-.DEBUGGED.zip)
I also deleted the mad horse, just in case, but I'm not sure if that's related.
If that solved it, then I would like to ask you something: have you noticed that "The Deserter" quest that happened before? What happened there, something strange? Did you have any other Empire-Related quest recently before that?
About the other errors, they might be related, or they might be because of a failed update. You can try deleting the recipes on your study desks, to see if that helps.

**Comment by ButternCream** [comment]
Hey jptrrs, the save is fixed now. I haven't payed much attention to the quests but I didnt notice anything strange. Then again I wasnt really paying attention to it. I'm not sure which quests have to do with empires specifically though.

**Comment by jptrrs** [comment]
Well, I was able to identify where the fault was, because the same thing was reported a couple times before. But I can only see the consequences, not the root cause, because I can't reproduce the issue.  When loaded with a clean mod list the offending pawn's expertise is generated and she springs to life (her name is Cosva, BTW, you can try this out with the faulty file).
This tells me there is some mod out there that causes this on some rare cases. I'd ask you to try step 3 to isolate what is causing that, if possible. Its a matter of loading mods in a ordered fashion and loading the file.

**Comment by ButternCream** [comment]
Sure I can give that a try. Would I need to change mods and make a new game or keep loading the broken save?

**Comment by jptrrs** [comment]
> Sure I can give that a try. Would I need to change mods and make a new game or keep loading the broken save?

Keep loading. You'd have to ignore a bunch of warnings for missing content, though... But that would make it evident what is causing the pawn to not spawn properly.

**Comment by ButternCream** [comment]
So I did a process of elimination by removing mods in small groups from the original list. What I found was

[Vanilla Weapons Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360) w/o HR works
[Vanilla Weapons Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360) with HR brings back error

[Misc Robots++](https://steamcommunity.com/sharedfiles/filedetails/?id=747645520) w/o HR works
[Misc Robots++](https://steamcommunity.com/sharedfiles/filedetails/?id=747645520) with HR brings back error

[Weapon Tech 1.1](https://steamcommunity.com/sharedfiles/filedetails/?id=2005456121) w/o HR works
[Weapon Tech 1.1](https://steamcommunity.com/sharedfiles/filedetails/?id=2005456121) with HR brings back error

- By "works" I mean it fixed the gui issue, horse issue and cosva issue. No longer show up in logs and I can click things.
- All three of those mods enabled together w/o HR works
- I tested each of those mods 1 by 1, meaning just one of those mods + HR with the other 2 disabled. 
- I also kept the mod order the same as I removed / re-added mods.
- All of those tests you can think of as me doing "Load mod list from save" -> do those tests ^.

I hope this helps. Let me know if I can try anything else

**Comment by jptrrs** [comment]
Great! I can deal with those 3. Thanks for narrowing it down!

Em qui, 2 de jul de 2020 02:54, Scott <notifications@github.com> escreveu:

**Comment by jptrrs** [comment]
Fixed for the next update.
It was a combination of factors causing an unexpected situation when certain pawns were generated. This fix makes the mod much more resilient, so it was totally worth it!
