### ISSUE TITLE
Error with SimpleSidearms

### ISSUE THREAD

**Issue by Paraxdq** [jptrrs/HumanResources#69]
Hello, 

having a blast playing with your mod, its a really nice additions to Rimworld!
Beside the lagging from the LearnWeapons Class which someone already mentioned I also got this error which I mostly can not reproduce. It happens randomly with one colonist who has one range and one melee weapon equiped via the simple side arms mod [Link to the Error Log Line](https://gist.github.com/HugsLibRecordKeeper/154e22f9548a30e1bd19973cd037f375#file-output_log-txt-L1589) and after its first occurrence it starts repeating every about 5 seconds.

Only way to find out which colonist is buggy is to draft all colonist until the error occures again with this error message [here](https://gist.github.com/HugsLibRecordKeeper/154e22f9548a30e1bd19973cd037f375#file-output_log-txt-L1600) where you can see that my colonist "Slick" was causing the issue.
Which fixes the problem until it occures again.

I could attach a save file too if needed.

Full HugsLib Log:
https://gist.github.com/154e22f9548a30e1bd19973cd037f375

**Comment by Paraxdq** [comment]
Maybe I found a hint, my colonist "Slick" is incapable of violence so she equipped an item as a tool and shes the only one who causes the problem so far.

**Comment by jptrrs** [comment]
Hi, Paraxdq! Thanks for reporting. I stumbled on that error on ocasion too, but also couldn't pinpoint the cause. You mentioned equiping a tool, what's the mod tool you're using? Survival Tools? That might be it.

**Comment by Paraxdq** [comment]
You're welcome, I had to check because I thought it was a vanilla axe which my colonist had equipped but it's instead the axe from vanilla weapons expanded. I don't use the survival tools mod. Didn't try to check it with other tools either, can do it tomorrow tho.

**Comment by jptrrs** [comment]
Hm, ok. I'll look into it.

**Comment by abrenneke** [comment]
I get this frequently too. 

https://github.com/jptrrs/HumanResources/blob/849f85d7161fa21f34f62af9e43e86534465e6a4/Source/Harmony/Compatibility/SimpleSidearms_Patches.cs#L29-L34

`weapon` is sometimes null. Not sure why that would be called with null, maybe when unequipping? Probably just returning true in that case would be fine?

**Comment by jptrrs** [comment]
You guys make it hard for me not to fix things =)
Following your tips, Paraxdq, I was able to reproduce it. The thing is Vanilla Expanded Weapons allows for a non-violent pawns to equip some weapons as a tool. Since it is in inventory, Simple Sidearms treats it like a weapon that could be equipped. If you draft the pawn and force him to use the weapon, that error pops up. Maybe some other conditions can have the same result, but that alignment of factors explains why the bug is rare.
Then, abrenneke, you solved it. Pretty simple fix once you figured out the weapon is coming up null.
Should be up on the next update.

**Comment by Paraxdq** [comment]
Glad to hear that you could fix it!
