### ISSUE TITLE
Prisoners restart documenting a tech each time instead of finshing

### ISSUE THREAD

**Issue by CodeheretichOther** [jptrrs/HumanResources#96]
![изображение](https://user-images.githubusercontent.com/66388882/98589915-175db280-22df-11eb-8e97-b1f2b0a97037.png)

Prison Labor prisoner won't finish documenting a tech after taking a break, instead starts a new unfinished document each time.
Hope you can fix this, getting techs from prisoners has always beenmy favorite part of the mod.

**Comment by jptrrs** [comment]
Yeah, this has been a problem since we simplified the whole recipe process. I should have added this to the list of known issues already. The thing is, with Prison Labor, the pawn doesn't get ownership over the recipe (you can confirm this by the lack of his name marking the bill once it is started), but our new system depends on that. 
I suggest you report it to Prison Labor's authors.
In the meantime, you can use the previous version, which seems unaffected: https://github.com/jptrrs/HumanResources/releases/tag/v0.15.3

**Comment by CodeheretichOther** [comment]
Cool, thanks for giving me the previous version!

For the time being, I've just switched to simple slavery and got rid of PL altogether, prisoners-turned-slaves don't seem to have any issues

**Comment by tophd7** [comment]
I have a fix for this, but I'm not sure how to do a harmony patch. I can send you the changes I made to fix the issue if you would like.

Edit for clarification: I stored the book in a variable and if the pawn is a prisoner I made them look for the bookUtf instead of the billUtf

Edit 2: Nevermind, a patch has been made on PL end that is on github, not sure when it will come to steam

**Comment by jptrrs** [comment]
Fixed by Prison Labor v1.2.3
